# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  adminkey:  # id of input
    description: 'Who to greet'
    required: true
  token:  # id of input
    description: 'Who to greet'
    required: true
runs:
  using: 'composite'
  steps:
    # Don't assume the admin key came from a secret so mask it for safety
    - name: mask
      shell: bash
      run: |
        env
        xx=${{ inputs.token }}
        echo ${{ toJSON(inputs) }}
        adminkey=$(jq -r '.adminkey' ${{ toJSON(inputs) }})
        echo "::add-mask::${adminkey}"
