name: BR
on:
  workflow_call:
  workflow_dispatch:
jobs:
  bra:
     runs-on: ubuntu-latest
     steps:
         - uses: actions/setup-node@v4
           with:
             node-version: '22'
         - run: date
         - uses: stepzen-dev/stepzen-install@v1
         - run: date
  
