on:
  push:
  schedule:
    - cron: "28 1/1 * * *"

jobs:
  extended-testing:
    runs-on: ubuntu-latest
    name: Extended testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Time of last commit
        id: committime
        run: |
          now=`date +%s`
          lct=`git show -s --format=%ct ${GITHUB_SHA}`
          let "since=${now} - ${lct}"
          echo ${since}
          let "four_hours=4*60*60"
          # Want 1 (shell false) to run tests
          run_tests=`test "${since}" -gt "${four_hours}"`
          echo ::set-env name=run_tests::${run_tests}
      - name: Skip tests
        id: no-recent-commit
        if: ${{ env.run_tests }} == 0
        run: |
          echo "No recent commit"
      - name: Running tests
        id: recent-commit
        if: ${{ env.run_tests} } == 1
        run: |
          echo "Recent commit"
