on:
  push:
  schedule:
    - cron: "28 1/1 * * *"

jobs:
  extended-testing:
    runs-on: ubuntu-latest
    name: Extended testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Time of last commit
        id: step_one
        run: |
          now=`date +%s`
          lct=`git show -s --format=%ct ${GITHUB_SHA}`
          let "elapsed=${now} - ${lct}"
          echo ${elapsed}
