on:
  push:
  schedule:
    - cron: "28 1/1 * * *"

jobs:
  extended-testing:
    runs-on: ubuntu-latest
    name: Extended testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Time of last commit
        id: ct
        run: |
          set -x
          now=`date +%s`
          lct=`git show -s --format=%ct ${GITHUB_SHA}`
          let "since=${now} - ${lct}"
          echo ${since}
          let "hours=4*60*60"
          run_tests=skip
          echo "h1"
          if [ "${since}" -lt "${hours}" ]; then run_tests=run; fi
          echo "h2-2"
          # echo "run_tests=${run_tests}" >> $GITHUB_ENV
          echo ::set-output name=run_test::${run_test}
      - name: Skip tests
        id: no-recent-commit
        if: steps.ct.outputs.run_tests == 'skip'
        run: |
          echo "No recent commit"
      - name: Running tests
        id: recent-commit
        if: steps.ct.outputs.run_tests == 'run'
        run: |
          echo "Recent commit"
