on:
  push:
  workflow_dispatch:
    inputs:
      my-var:
        type: string

env:
  TAG: ${{ inputs.my-var || 'abc' }}
jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - name: check-env
        run: env
