name: New Issues

on:
  issues:
    types:
      - opened
      - transfered
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'issues'
        run: |
          echo 'Issue' ${{ github.event.issue }}
          echo 'Number' ${{ github.event.issue.number }}
          echo 'Title' ${{ github.event.issue.title }}
          echo 'URL' ${{ github.event.issue.url }}
          echo $(printf "%s/%s/issues/%s", "${{ github.server_url }}" "${{ github.repository }}" "${{ github.event.issue.number }}" )
      - if: github.event_name == 'pull_request' && github.event.pull_request.isDraft == false
        run: |
          echo 'Number' ${{ github.event.pull_request.number }}
          echo 'Action' ${{ github.event.action }}
          echo 'Title' ${{ github.event.pull_request.title }}
          echo 'Draft' ${{ github.event.pull_request.isDraft }}
          echo 'URL' ${{ github.event.pull_request.url }}
          echo $(printf "%s/%s/pull/%s", "${{ github.server_url }}" "${{ github.repository }}" "${{ github.event.pull_request.number }}" )
