name: M
on:
  workflow_dispatch:
    inputs:
      envvars:
        required: false
        default: "{}"
        type: string
jobs:
  mat:
     strategy:
       matrix:
         fruit: [apple]
         animal: [cat]
     uses: ./.github/workflows/mj.yaml
     with:
       fruit: ${{ matrix.fruit }}
       animal: ${{ matrix.animal }}
       evs: '${{ format(''{{ "A1": "{0}", "A2": "{1}" }}'', matrix.fruit, matrix.animal ) }}'
