name: M
on:
  workflow_dispatch:
jobs:
  bra:
     strategy:
       matrix:
         fruit: [apple, pear]
         animal: [cat, dog]
         include:
           - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
     runs-on: ubuntu-latest
     steps:
       - run: |
          echo ${{ matrix }}
