name: M
on:
  workflow_dispatch:
jobs:
  mat:
     timeout-minutes: 2
     strategy:
       matrix:
         fruit: [apple]
         animal: [cat]
     runs-on: ubuntu-latest
     steps:
       - run: |
          echo fruit ${{ matrix.fruit }}
          echo animal ${{ matrix.animal }}
          sleep 600
