name: M
on:
  workflow_dispatch:
jobs:
  mat:
     strategy:
       matrix:
         fruit: [apple, pear]
         animal: [cat, dog]
         include:
           - color: pink
             animal: cat
           - fruit: banana
             animal: wolf
             color: teal
     runs-on: ubuntu-latest
     steps:
       - run: |
          echo ${{ matrix }}
