name: M
on:
  workflow_dispatch:
    inputs:
      envvars:
        required: false
        type: string
jobs:
  mat:
     strategy:
       matrix:
         fruit: [apple]
         animal: [cat]
     runs-on: ubuntu-latest
     steps:
       - run: |
          echo fruit ${{ matrix.fruit }}
          echo animal ${{ matrix.animal }}
          env
         env: ${{ fromJSON(inputs.envvars) }}
