name: M
on:
  workflow_dispatch:
    inputs:
      envvars:
        required: false
        default: "{}"
        type: string
jobs:
  mat:
     strategy:
       matrix:
         fruit: [apple]
         animal: [cat]
     runs-on: ubuntu-latest
     steps:
       - run: |
          echo fruit ${{ matrix.fruit }}
          echo animal ${{ matrix.animal }}
          echo 'ENV'
          # env | grep STEPZEN
          echo 'JSON'
          echo ${{ format('{{ "A1": {0}, "A2": {1} }}', matrix.fruit, matrix.animal ) }}
         # env: ${{ fromJSON(toJSON()) }}
