name: M
on:
  workflow_dispatch:
jobs:
  mat:
     strategy:
       matrix:
         fruit: [apple, pear]
         animal: [cat, dog]
         color: [pink]
         include:
           - color: blue
             animal: cat
           - fruit: banana
             animal: wolf
             color: teal
     runs-on: ubuntu-latest
     steps:
       - run: |
          echo fruit ${{ matrix.fruit }}
          echo animal ${{ matrix.animal }}
          echo color ${{ matrix.color }}
