on: [push]

jobs:
  hello_world_job:
    environment: Danville
    runs-on: ubuntu-latest
    name: Deploy StepZen empty schema
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy StepZen
        uses: ./actions/stepzen-cli
        id: deploy-empty
        with:
          account: ${{ secrets.SZ_ACCOUNT }}
          adminkey: ${{ secrets.SZ_ADMIN_KEY }}
          dir: schemas/empty
          endpoint: deploy/test
