on: [push]

jobs:
  hello_world_job:
    environment: Danville
    runs-on: ubuntu-latest
    name: Deploy StepZen empty schema
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test dvd
        uses: ./actions/dvd
        id: deploy-dvd
