on:
  workflow_dispatch:

jobs:
  hello_world_job:
    environment: Danville
    runs-on: ubuntu-latest
    name: Deploy StepZen empty schema
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - run: curl https://danville.stepzen.net/api/edgy-ibis/__graphql --header "Content-Type: application/json" --data-raw '{ "query": "{me{clientIp} }" }'
