name: N
on:
  push:
  workflow_dispatch:
    inputs:
      d1:
        required: true
        default: true
        type: boolean
      d2:
        required: true
        default: true
        type: boolean
env:
  D1: ${{ github.event_name == 'workflow_dispatch' && inputs.d1 || true }}
  D2: ${{ github.event_name == 'workflow_dispatch' && inputs.d2 || true }}

jobs:
  nn:
    runs-on: ubuntu-latest
    steps:
      - run: echo "D1 is" ${D1}
      - run: echo "D2 is" ${D2}
