name: TestCheck
on:
   pull_request:
     types: [opened, synchronize, reopened]

jobs:
  ddcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./actions/hello
      with:
       adminkey: "super-tokern"
