name: TestCheck
on:
   pull_request:
     types: [opened, synchronize, reopened]

jobs:
  ddcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: stepzen-dev/stepzen-install@v1
    - uses: stepzen-dev/stepzen-login@fbd443909257993ef72ec459f540b9a705d250e4
      with:
       domain: "us-east-a.ibm.stepzen.net"
       account: "danville"
       adminkey: ${{ secrets.SZDAN2 }}
