name: TestCheck
on:
   pull_request:
     types: [opened, synchronize, reopened]

jobs:
  ddcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: bash ./ok.sh
    - uses: stepzen-dev/stepzen-install@v1
    - uses: stepzen-dev/stepzen-login@1c112dbfd8ac3e14bb4fb93b699600a35e9c0da1
      with:
       domain: "us-"
       account: "abc"
       adminkey: "super-tokern"
