# action.yml
name: "StepZen Deploy"
description: "Deploy a StepZen schema"
inputs:
  account:
    description: "account environment secrets variable name"
    required: true
  adminkey:
    description: "admin key environment secrets variable name"
    required: true
  dir:
    description: "directory"
    required: true
    default: "."
  endpoint: # id of input
    description: "endpoint"
    required: true
    default: "test/test"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.account }}
    - ${{ inputs.adminkey" }}
    - ${{ inputs.dir }}
    - ${{ inputs.endpoint }}
